cosmic_user_name=""
cosmic_password=""

nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-5 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_5 --add_reference false --final_database_protein PXD005946-Sample-55.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name RXF393 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values RXF393 --add_reference false --final_database_protein PXD005942-Sample-40.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MCF7 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MCF7 --add_reference false --final_database_protein PXD005942-Sample-54.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A498 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A498 --add_reference false --final_database_protein PXD005942-Sample-55.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H23 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H23 --add_reference false --final_database_protein PXD005946-Sample-40.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MCF7 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MCF7 --add_reference false --final_database_protein PXD005946-Sample-54.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HOP-92 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HOP_92 --add_reference false --final_database_protein PXD005946-Sample-56.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SF539 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SF539 --add_reference false --final_database_protein PXD005942-Sample-57.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name KM12 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values KM12 --add_reference false --final_database_protein PXD005942-Sample-42.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-4 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_4 --add_reference false --final_database_protein PXD005942-Sample-56.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SF268 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SF268 --add_reference false --final_database_protein PXD005946-Sample-57.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name TK10 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values TK10 --add_reference false --final_database_protein PXD005946-Sample-43.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name ACHN --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values ACHN --add_reference false --final_database_protein PXD005946-Sample-47.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MOLT-4 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MOLT_4 --add_reference false --final_database_protein PXD005946-Sample-53.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD002395-Sample-26.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-8 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_8 --add_reference false --final_database_protein PXD005942-Sample-52.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MCF7 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MCF7 --add_reference false --final_database_protein PXD005942-Sample-46.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name ACHN --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values ACHN --add_reference false --final_database_protein PXD005942-Sample-47.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H522 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H522 --add_reference false --final_database_protein PXD005942-Sample-53.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SF295 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SF295 --add_reference false --final_database_protein PXD005946-Sample-52.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H322M --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H322M --add_reference false --final_database_protein PXD005946-Sample-46.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SF539 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SF539 --add_reference false --final_database_protein PXD005946-Sample-50.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HOP-92 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HOP_92 --add_reference false --final_database_protein PXD005946-Sample-44.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name CAKI-1 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values CAKI_1 --add_reference false --final_database_protein PXD005942-Sample-45.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SNB75 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SNB75 --add_reference false --final_database_protein PXD005942-Sample-51.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HCC2998 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HCC2998 --add_reference false --final_database_protein PXD005942-Sample-50.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name COLO-205 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values COLO205 --add_reference false --final_database_protein PXD005942-Sample-44.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HCT-116 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HCT_116 --add_reference false --final_database_protein PXD005946-Sample-45.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name RPMI-8226 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values RPMI_8226 --add_reference false --final_database_protein PXD005946-Sample-51.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SW620 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SW620 --add_reference false --final_database_protein PXD005946-Sample-36.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-MEL-5 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_MEL_5 --add_reference false --final_database_protein PXD005946-Sample-22.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005698-Sample-3.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name IGROV-1 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values IGROV1 --add_reference false --final_database_protein PXD005942-Sample-23.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name TK10 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values TK10 --add_reference false --final_database_protein PXD005942-Sample-37.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SF268 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SF268 --add_reference false --final_database_protein PXD005942-Sample-5.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HOP-92 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HOP_92 --add_reference false --final_database_protein PXD005942-Sample-4.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HT-29 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HT29 --add_reference false --final_database_protein PXD005942-Sample-36.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SN12C --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SN12C --add_reference false --final_database_protein PXD005942-Sample-22.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005698-Sample-2.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-OV-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_OV_3 --add_reference false --final_database_protein PXD005946-Sample-23.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005946-Sample-37.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name U251 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values U251 --add_reference false --final_database_protein PXD005946-Sample-21.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HL-60 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HL_60 --add_reference false --final_database_protein PXD005946-Sample-35.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name CCRF-CEM --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values CCRF_CEM --add_reference false --final_database_protein PXD005940-Sample-9.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name DU-145 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values DU_145 --add_reference false --final_database_protein PXD005942-Sample-34.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name UACC-62 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values UACC_62 --add_reference false --final_database_protein PXD005942-Sample-20.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HL-60 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HL_60 --add_reference false --final_database_protein PXD005942-Sample-6.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name T47D --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values T47D --add_reference false --final_database_protein PXD005942-Sample-7.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H460 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H460 --add_reference false --final_database_protein PXD005942-Sample-21.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name RPMI-8226 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values RPMI_8226 --add_reference false --final_database_protein PXD005942-Sample-35.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005698-Sample-1.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MCF7 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MCF7 --add_reference false --final_database_protein PXD005940-Sample-8.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name 786-0 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values 786_0 --add_reference false --final_database_protein PXD005946-Sample-34.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name RXF393 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values RXF393 --add_reference false --final_database_protein PXD005946-Sample-20.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name DU-145 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values DU_145 --add_reference false --final_database_protein PXD005946-Sample-24.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name UACC-62 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values UACC_62 --add_reference false --final_database_protein PXD005946-Sample-30.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HT-29 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HT29 --add_reference false --final_database_protein PXD005946-Sample-18.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005698-Sample-5.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name CCRF-CEM --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values CCRF_CEM --add_reference false --final_database_protein PXD005942-Sample-31.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name PC-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values PC_3 --add_reference false --final_database_protein PXD005942-Sample-25.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name 786-0 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values 786_0 --add_reference false --final_database_protein PXD005942-Sample-19.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HOP-62 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HOP_62 --add_reference false --final_database_protein PXD005942-Sample-3.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name EKVX --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values EKVX --add_reference false --final_database_protein PXD005942-Sample-2.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-5 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_5 --add_reference false --final_database_protein PXD005942-Sample-18.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H23 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H23 --add_reference false --final_database_protein PXD005942-Sample-24.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HCT-116 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HCT_116 --add_reference false --final_database_protein PXD005942-Sample-30.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005698-Sample-4.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H226 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H226 --add_reference false --final_database_protein PXD005946-Sample-19.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name COLO-205 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values COLO205 --add_reference false --final_database_protein PXD005946-Sample-31.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_3 --add_reference false --final_database_protein PXD005946-Sample-25.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-MEL-2 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_MEL_2 --add_reference false --final_database_protein PXD005946-Sample-27.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SF295 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SF295 --add_reference false --final_database_protein PXD005942-Sample-26.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-OV-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_OV_3 --add_reference false --final_database_protein PXD005942-Sample-32.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HOP-62 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HOP_62 --add_reference false --final_database_protein PXD005946-Sample-8.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-MEL-28 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_MEL_28 --add_reference false --final_database_protein PXD005946-Sample-9.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name K-562 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values K_562 --add_reference false --final_database_protein PXD005942-Sample-1.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MOLT-4 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MOLT_4 --add_reference false --final_database_protein PXD005942-Sample-33.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SR --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SR --add_reference false --final_database_protein PXD005942-Sample-27.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD002395-Sample-1.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name IGROV-1 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values IGROV1 --add_reference false --final_database_protein PXD005946-Sample-26.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name UACC-257 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values UACC_257 --add_reference false --final_database_protein PXD005946-Sample-32.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MCF7 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MCF7 --add_reference false --final_database_protein PXD005946-Sample-17.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name PC-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values PC_3 --add_reference false --final_database_protein PXD005940-Sample-3.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name LOXIMVI --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values LOXIMVI --add_reference false --final_database_protein PXD005942-Sample-16.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name Hs-578-T --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HS578T --add_reference false --final_database_protein PXD005946-Sample-4.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name K-562 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values K_562 --add_reference false --final_database_protein PXD005946-Sample-5.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name RXF393 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values RXF393 --add_reference false --final_database_protein PXD005940-Sample-2.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name M14 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values M14 --add_reference false --final_database_protein PXD005946-Sample-16.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H69  --add_reference false --final_database_protein PXD015270-Sample-4.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SR --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SR --add_reference false --final_database_protein PXD005946-Sample-28.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name LOXIMVI --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values LOXIMVI --add_reference false --final_database_protein PXD005946-Sample-14.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_3 --add_reference false --final_database_protein PXD005942-Sample-29.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name UACC-257 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values UACC_257 --add_reference false --final_database_protein PXD005942-Sample-15.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name EKVX --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values EKVX --add_reference false --final_database_protein PXD005946-Sample-7.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name BT-549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values BT_549 --add_reference false --final_database_protein PXD005946-Sample-6.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SW620 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SW620 --add_reference false --final_database_protein PXD005942-Sample-14.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-MEL-2 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_MEL_2 --add_reference false --final_database_protein PXD005942-Sample-28.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name COLO-205 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values COLO205 --add_reference false --final_database_protein PXD005940-Sample-1.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SNB75 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SNB75 --add_reference false --final_database_protein PXD005946-Sample-15.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-4 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_4 --add_reference false --final_database_protein PXD005946-Sample-29.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name CCRF-CEM --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values CCRF_CEM --add_reference false --final_database_protein PXD005946-Sample-39.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD015270-Sample-1.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name U251 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values U251 --add_reference false --final_database_protein PXD005940-Sample-5.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name Hs-578-T --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HS578T --add_reference false --final_database_protein PXD005942-Sample-10.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H322M --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H322M --add_reference false --final_database_protein PXD005942-Sample-38.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HCC2998 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HCC2998 --add_reference false --final_database_protein PXD005946-Sample-2.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SN12C --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SN12C --add_reference false --final_database_protein PXD005946-Sample-3.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H226 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H226 --add_reference false --final_database_protein PXD005942-Sample-39.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name BT-549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values BT_549 --add_reference false --final_database_protein PXD005942-Sample-11.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H460 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H460 --add_reference false --final_database_protein PXD005940-Sample-4.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A498 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A498 --add_reference false --final_database_protein PXD005946-Sample-38.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name T47D --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values T47D --add_reference false --final_database_protein PXD005946-Sample-10.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SR --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SR --add_reference false --final_database_protein PXD005946-Sample-12.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H1975  --add_reference false --final_database_protein PXD015270-Sample-2.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-OV-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_OV_3 --add_reference false --final_database_protein PXD005940-Sample-6.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MDA-MB-231 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MDA_MB_231 --add_reference false --final_database_protein PXD005942-Sample-13.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD005942-Sample-9.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H522 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H522 --add_reference false --final_database_protein PXD005946-Sample-1.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MDA-MB-453  --add_reference false --final_database_protein PXD005942-Sample-8.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-MEL-28 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_MEL_28 --add_reference false --final_database_protein PXD005942-Sample-12.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name M14 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values M14 --add_reference false --final_database_protein PXD005940-Sample-7.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H446  --add_reference false --final_database_protein PXD015270-Sample-3.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name MDA-MB-231 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values MDA_MB_231 --add_reference false --final_database_protein PXD005946-Sample-13.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HCT-15 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HCT_15 --add_reference false --final_database_protein PXD005946-Sample-48.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name PC-3 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values PC_3 --add_reference false --final_database_protein PXD005946-Sample-60.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name U251 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values U251 --add_reference false --final_database_protein PXD005942-Sample-49.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name HCT-15 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values HCT_15 --add_reference false --final_database_protein PXD005942-Sample-48.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name A549 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values A549 --add_reference false --final_database_protein PXD002395-Sample-14.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name KM12 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values KM12 --add_reference false --final_database_protein PXD005946-Sample-61.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name CAKI-1 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values CAKI_1 --add_reference false --final_database_protein PXD005946-Sample-49.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name OVCAR-8 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values OVCAR_8 --add_reference false --final_database_protein PXD005946-Sample-59.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name M14 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values M14 --add_reference false --final_database_protein PXD005942-Sample-58.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name SK-MEL-5 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values SK_MEL_5 --add_reference false --final_database_protein PXD005942-Sample-59.fa --outdir sample_specific_dbs -resume
                
nextflow main.nf -profile docker --cosmic_celllines true --cosmic_user_name $cosmic_user_name --cosmic_password $cosmic_password --cosmic_cellline_name NCI-H460 --cbioportal true --cbioportal_filter_column SAMPLE_ID --cbioportal_study_id cellline_nci60 --cbioportal_accepted_values NCI_H460 --add_reference false --final_database_protein PXD005946-Sample-58.fa --outdir sample_specific_dbs -resume
                
Final database: refprot + ncrna
nextflow main.nf -profile docker --ensembl_name homo_sapiens --ncrna true --pseudogenes true --altorfs true --final_database_protein refprot_altorfs_ncrna_pesudogenes.fa.fa --outdir sample_specific_dbs -resume
